[window]
padding = { x = 5, y = 5 }
opacity = 0.85
blur = true
startup_mode = "Maximized"
resize_increments = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "Hack"
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u0017"
