[window]
padding = { x = 5, y = 5 }
startup_mode = "Maximized"
resize_increments = true
dynamic_title = true
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono NL"
normal.style = "Regular"
bold.style = "Regular"
italic.style = "Regular"
bold_italic.style = "Regular"
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500

[colors.primary]
background = '#000000'
foreground = '#aaaaaa'

[colors.normal]
black = '#000000'
red = '#aa0000'
green = '#00aa00'
yellow = '#aa5500'
blue = '#0000aa'
magenta = '#aa00aa'
cyan = '#00aaaa'
white = '#aaaaaa'

[colors.bright]
black = '#555555'
red = '#ff5555'
green = '#55ff55'
yellow = '#ffff55'
blue = '#5555ff'
magenta = '#ff55ff'
cyan = '#55ffff'
white = '#ffffff'
