[window]
opacity = 1
padding.x = 5
padding.y = 5
decorations = "Full"
decorations_theme_variant = "None"
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "Hack"
normal.style = "Regular"
bold.family = "Hack"
bold.style = "Bold"
italic.family = "Hack"
italic.style = "Italic"
bold_italic.family = "Hack"
bold_italic.style = "Bold Italic"
size = 15

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u0017"

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500

[colors.primary]
background = "#181818"
foreground = "#ffffff"
