[window]
padding = { x = 5, y = 5 }
opacity = 0.85
blur = true
startup_mode = "Maximized"
resize_increments = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "Hack"
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500
